language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update --prefer-source PREFER_LOWEST

script:
  - bin/phpspec run -v -f pretty
